### PR TITLE
Added exe icons, file associations, etc

### PR DESCRIPTION
**Pull request by lafleurh**
# 4.1.0
 * Add icon extraction from exe
 * Associate extensions with exe
 * Better support for semantic version to Windows version
 * Fix all unit tests so that mock-fs works with jest

### CODE REVIEW

**Comment by lafleurh** [comment]
I would like to merge these changes because I am looking to include changes in this project: https://github.com/ElectronNET/Electron.NET that depend on them.

**Comment by ezequielvictor** [comment]
+1

**Comment by JBloss1517** [comment]
Can this be merged? I, too, need this functionality!

**Comment by VerteDinde** [comment]
Hey @lafleurh, thanks so much for the PR! We'll review this for you this week, sorry for the wait

**Comment by felixrieseberg** [comment]
It only took me three years 😆 I'm so sorry, I've been gone for a minute.

**Pull request merged**
